### YamlMime:UniversalReference
items:
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode:enum'
    summary: 自定义函数的错误代码。 这些错误将出现在调用函数的单元格中。
    name: CustomFunctions.ErrorCode
    fullName: CustomFunctions.ErrorCode
    langs:
      - typeScript
    type: enum
    package: custom-functions-runtime!
    children:
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
      - 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member'
    summary: '此错误代码指示使用的函数被零或空单元格除。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/overview/visio-javascript-reference-overview)\]'
    name: divisionByZero
    fullName: divisionByZero
    langs:
      - typeScript
    type: field
    numericValue: '"#DIV/0!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member'
    summary: '函数名称中有拼写错误。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: invalidName
    fullName: invalidName
    langs:
      - typeScript
    type: field
    numericValue: '"#NAME?"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member'
    summary: '函数中使用的数字有问题。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: invalidNumber
    fullName: invalidNumber
    langs:
      - typeScript
    type: field
    numericValue: '"#NUM!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member'
    summary: '函数引用了无效的单元格。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: invalidReference
    fullName: invalidReference
    langs:
      - typeScript
    type: field
    numericValue: '"#REF!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member'
    summary: '此错误代码指示函数中使用的值的数据类型错误。 如果需要，还可以使用自定义错误消息来替代错误代码。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: invalidValue
    fullName: invalidValue
    langs:
      - typeScript
    type: field
    numericValue: '"#VALUE!"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member'
    summary: '此错误代码指示函数或服务不可用。 如果需要，还可以使用自定义错误消息来替代错误代码。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: notAvailable
    fullName: notAvailable
    langs:
      - typeScript
    type: field
    numericValue: '"#N/A"'
  - uid: 'custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member'
    summary: '函数中的区域不相交。 无法使用自定义错误消息。 \[[API 集： CustomFunctionsRuntime 1.3](/office/dev/add-ins/reference/javascript-api-for-office)\]'
    name: nullReference
    fullName: nullReference
    langs:
      - typeScript
    type: field
    numericValue: '"#NULL!"'